name: Subir informes

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  informes:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        rama: [tp1, tp2, tp3]
        include:
          - rama: tp1
            nombre: TP1
          - rama: tp2
            nombre: TP2
          - rama: tp3
            nombre: TP3
    steps:
      - name: Conseguir repo en la rama del tp1
        uses: actions/checkout@v4
        with:
          ref: ${{ matrix.rama }}

      - name: Crear el pdf
        uses: addnab/docker-run-action@v3
        timeout-minutes: 5
        with:
          image: juanbiancuzzo/latex:latest
          options: -v ${{ github.workspace }}/Informe:/latex
          run: sh -c "/scripts/compile.sh && cp /latex/main.pdf /latex/${{ matrix.nombre }}-Grupo2.pdf"

      - name: Subir pdf a github artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.nombre }}
          path: ${{ github.workspace }}/Informe/${{ matrix.nombre }}-Grupo2.pdf
          if-no-files-found: warn

  release:
    needs: informes
    runs-on: ubuntu-latest

    steps:
      - name: Descargar artifact del TP1
        uses: actions/download-artifact@v4
        with:
          name: TP1
          path: .

      - name: Descargar artifact del TP2
        uses: actions/download-artifact@v4
        with:
          name: TP2
          path: .

      - name: Descargar artifact del TP3
        uses: actions/download-artifact@v4
        with:
          name: TP3
          path: .

      - name: Subir artifact como release asset
        uses: softprops/action-gh-release@v2
        with:
          tag_name: informe
          name: "Release informe"
          files: |
            **/TP1-Grupo2.pdf
            **/TP2-Grupo2.pdf
            **/TP3-Grupo2.pdf
